version: "3.7"

services:
  energy-imp:
    container_name: energy-imp
    build: './app/php/'
    ports:
      - "8123:80"
    restart: unless-stopped
    volumes:
      - ./app/public/:/var/www/html/
      - ./app/private/:/var/www/private/
